//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNubiaV0._1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos_GrupoGimnasio
    {
        public Alumnos_GrupoGimnasio()
        {
            this.Asistencias = new HashSet<Asistencia>();
        }
    
        public string Matricula { get; set; }
        public int idGimnasio { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual GrupoGimnasio GrupoGimnasio { get; set; }
        public virtual ICollection<Asistencia> Asistencias { get; set; }
    }
}
