//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNubiaV0._1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoGimnasio
    {
        public GrupoGimnasio()
        {
            this.Alumnos_GrupoGimnasio = new HashSet<Alumnos_GrupoGimnasio>();
        }
    
        public int idGimnasio { get; set; }
        public string nombre { get; set; }
        public int IdHorario { get; set; }
    
        public virtual ICollection<Alumnos_GrupoGimnasio> Alumnos_GrupoGimnasio { get; set; }
        public virtual HorarioGimnasio HorarioGimnasio { get; set; }
    }
}
