//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNubiaV0._1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Alumnoes = new HashSet<Alumno>();
        }
    
        public string Nombre { get; set; }
        public int IdLicenciatura { get; set; }
        public int idGrupo { get; set; }
        public string semestre { get; set; }
    
        public virtual ICollection<Alumno> Alumnoes { get; set; }
        public virtual Licenciatura Licenciatura { get; set; }
    }
}
