//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNubiaV0._1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenciatura
    {
        public Licenciatura()
        {
            this.Grupoes = new HashSet<Grupo>();
        }
    
        public int IdLicenciatura { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Grupo> Grupoes { get; set; }
    }
}
