//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNubiaV0._1.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistema_GimnasioEntities : DbContext
    {
        public Sistema_GimnasioEntities()
            : base("name=Sistema_GimnasioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alumno> Alumnoes { get; set; }
        public DbSet<Alumnos_GrupoGimnasio> Alumnos_GrupoGimnasio { get; set; }
        public DbSet<Asistencia> Asistencias { get; set; }
        public DbSet<Grupo> Grupoes { get; set; }
        public DbSet<GrupoGimnasio> GrupoGimnasios { get; set; }
        public DbSet<HorarioGimnasio> HorarioGimnasios { get; set; }
        public DbSet<HorarioGimnasio_Horas> HorarioGimnasio_Horas { get; set; }
        public DbSet<Hora> Horas { get; set; }
        public DbSet<Licenciatura> Licenciaturas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
