#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="biblioteca")]
public partial class BibliotecaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertAreas2(Areas2 instance);
  partial void UpdateAreas2(Areas2 instance);
  partial void DeleteAreas2(Areas2 instance);
  partial void InsertLibros2(Libros2 instance);
  partial void UpdateLibros2(Libros2 instance);
  partial void DeleteLibros2(Libros2 instance);
  partial void InsertUsuarios2(Usuarios2 instance);
  partial void UpdateUsuarios2(Usuarios2 instance);
  partial void DeleteUsuarios2(Usuarios2 instance);
  partial void InsertPrestamos2(Prestamos2 instance);
  partial void UpdatePrestamos2(Prestamos2 instance);
  partial void DeletePrestamos2(Prestamos2 instance);
  partial void InsertSanciones2(Sanciones2 instance);
  partial void UpdateSanciones2(Sanciones2 instance);
  partial void DeleteSanciones2(Sanciones2 instance);
  partial void InsertDetallePrestamos2(DetallePrestamos2 instance);
  partial void UpdateDetallePrestamos2(DetallePrestamos2 instance);
  partial void DeleteDetallePrestamos2(DetallePrestamos2 instance);
  #endregion
	
	public BibliotecaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bibliotecaConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BibliotecaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Areas2> Areas2
	{
		get
		{
			return this.GetTable<Areas2>();
		}
	}
	
	public System.Data.Linq.Table<Libros2> Libros2
	{
		get
		{
			return this.GetTable<Libros2>();
		}
	}
	
	public System.Data.Linq.Table<Usuarios2> Usuarios2
	{
		get
		{
			return this.GetTable<Usuarios2>();
		}
	}
	
	public System.Data.Linq.Table<Prestamos2> Prestamos2
	{
		get
		{
			return this.GetTable<Prestamos2>();
		}
	}
	
	public System.Data.Linq.Table<Sanciones2> Sanciones2
	{
		get
		{
			return this.GetTable<Sanciones2>();
		}
	}
	
	public System.Data.Linq.Table<DetallePrestamos2> DetallePrestamos2
	{
		get
		{
			return this.GetTable<DetallePrestamos2>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Areas")]
public partial class Areas2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _areCodigo;
	
	private string _areNombre;
	
	private int _areTiempo;
	
	private EntitySet<Libros2> _Libros2;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareCodigoChanging(int value);
    partial void OnareCodigoChanged();
    partial void OnareNombreChanging(string value);
    partial void OnareNombreChanged();
    partial void OnareTiempoChanging(int value);
    partial void OnareTiempoChanged();
    #endregion
	
	public Areas2()
	{
		this._Libros2 = new EntitySet<Libros2>(new Action<Libros2>(this.attach_Libros2), new Action<Libros2>(this.detach_Libros2));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int areCodigo
	{
		get
		{
			return this._areCodigo;
		}
		set
		{
			if ((this._areCodigo != value))
			{
				this.OnareCodigoChanging(value);
				this.SendPropertyChanging();
				this._areCodigo = value;
				this.SendPropertyChanged("areCodigo");
				this.OnareCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string areNombre
	{
		get
		{
			return this._areNombre;
		}
		set
		{
			if ((this._areNombre != value))
			{
				this.OnareNombreChanging(value);
				this.SendPropertyChanging();
				this._areNombre = value;
				this.SendPropertyChanged("areNombre");
				this.OnareNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areTiempo", DbType="Int NOT NULL")]
	public int areTiempo
	{
		get
		{
			return this._areTiempo;
		}
		set
		{
			if ((this._areTiempo != value))
			{
				this.OnareTiempoChanging(value);
				this.SendPropertyChanging();
				this._areTiempo = value;
				this.SendPropertyChanged("areTiempo");
				this.OnareTiempoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Areas2_Libros2", Storage="_Libros2", ThisKey="areCodigo", OtherKey="areCodigo")]
	public EntitySet<Libros2> Libros2
	{
		get
		{
			return this._Libros2;
		}
		set
		{
			this._Libros2.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Libros2(Libros2 entity)
	{
		this.SendPropertyChanging();
		entity.Areas2 = this;
	}
	
	private void detach_Libros2(Libros2 entity)
	{
		this.SendPropertyChanging();
		entity.Areas2 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libros")]
public partial class Libros2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _libCodigo;
	
	private string _libNombre;
	
	private int _libNumPag;
	
	private string _libAutor;
	
	private string _libEditorial;
	
	private int _areCodigo;
	
	private EntitySet<DetallePrestamos2> _DetallePrestamos2;
	
	private EntityRef<Areas2> _Areas2;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlibCodigoChanging(int value);
    partial void OnlibCodigoChanged();
    partial void OnlibNombreChanging(string value);
    partial void OnlibNombreChanged();
    partial void OnlibNumPagChanging(int value);
    partial void OnlibNumPagChanged();
    partial void OnlibAutorChanging(string value);
    partial void OnlibAutorChanged();
    partial void OnlibEditorialChanging(string value);
    partial void OnlibEditorialChanged();
    partial void OnareCodigoChanging(int value);
    partial void OnareCodigoChanged();
    #endregion
	
	public Libros2()
	{
		this._DetallePrestamos2 = new EntitySet<DetallePrestamos2>(new Action<DetallePrestamos2>(this.attach_DetallePrestamos2), new Action<DetallePrestamos2>(this.detach_DetallePrestamos2));
		this._Areas2 = default(EntityRef<Areas2>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int libCodigo
	{
		get
		{
			return this._libCodigo;
		}
		set
		{
			if ((this._libCodigo != value))
			{
				this.OnlibCodigoChanging(value);
				this.SendPropertyChanging();
				this._libCodigo = value;
				this.SendPropertyChanged("libCodigo");
				this.OnlibCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string libNombre
	{
		get
		{
			return this._libNombre;
		}
		set
		{
			if ((this._libNombre != value))
			{
				this.OnlibNombreChanging(value);
				this.SendPropertyChanging();
				this._libNombre = value;
				this.SendPropertyChanged("libNombre");
				this.OnlibNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libNumPag", DbType="Int NOT NULL")]
	public int libNumPag
	{
		get
		{
			return this._libNumPag;
		}
		set
		{
			if ((this._libNumPag != value))
			{
				this.OnlibNumPagChanging(value);
				this.SendPropertyChanging();
				this._libNumPag = value;
				this.SendPropertyChanged("libNumPag");
				this.OnlibNumPagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libAutor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string libAutor
	{
		get
		{
			return this._libAutor;
		}
		set
		{
			if ((this._libAutor != value))
			{
				this.OnlibAutorChanging(value);
				this.SendPropertyChanging();
				this._libAutor = value;
				this.SendPropertyChanged("libAutor");
				this.OnlibAutorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libEditorial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string libEditorial
	{
		get
		{
			return this._libEditorial;
		}
		set
		{
			if ((this._libEditorial != value))
			{
				this.OnlibEditorialChanging(value);
				this.SendPropertyChanging();
				this._libEditorial = value;
				this.SendPropertyChanged("libEditorial");
				this.OnlibEditorialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areCodigo", DbType="Int NOT NULL")]
	public int areCodigo
	{
		get
		{
			return this._areCodigo;
		}
		set
		{
			if ((this._areCodigo != value))
			{
				if (this._Areas2.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnareCodigoChanging(value);
				this.SendPropertyChanging();
				this._areCodigo = value;
				this.SendPropertyChanged("areCodigo");
				this.OnareCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libros2_DetallePrestamos", Storage="_DetallePrestamos2", ThisKey="libCodigo", OtherKey="libCodigo")]
	public EntitySet<DetallePrestamos2> DetallePrestamos2
	{
		get
		{
			return this._DetallePrestamos2;
		}
		set
		{
			this._DetallePrestamos2.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Areas2_Libros2", Storage="_Areas2", ThisKey="areCodigo", OtherKey="areCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Areas2 Areas2
	{
		get
		{
			return this._Areas2.Entity;
		}
		set
		{
			Areas2 previousValue = this._Areas2.Entity;
			if (((previousValue != value) 
						|| (this._Areas2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Areas2.Entity = null;
					previousValue.Libros2.Remove(this);
				}
				this._Areas2.Entity = value;
				if ((value != null))
				{
					value.Libros2.Add(this);
					this._areCodigo = value.areCodigo;
				}
				else
				{
					this._areCodigo = default(int);
				}
				this.SendPropertyChanged("Areas2");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DetallePrestamos2(DetallePrestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Libros2 = this;
	}
	
	private void detach_DetallePrestamos2(DetallePrestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Libros2 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
public partial class Usuarios2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _usuDocumento;
	
	private string _usuNombre;
	
	private string _usuDireccion;
	
	private string _usuTelefono;
	
	private string _usuCorreo;
	
	private string _usuEstado;
	
	private EntitySet<Prestamos2> _Prestamos;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuDocumentoChanging(int value);
    partial void OnusuDocumentoChanged();
    partial void OnusuNombreChanging(string value);
    partial void OnusuNombreChanged();
    partial void OnusuDireccionChanging(string value);
    partial void OnusuDireccionChanged();
    partial void OnusuTelefonoChanging(string value);
    partial void OnusuTelefonoChanged();
    partial void OnusuCorreoChanging(string value);
    partial void OnusuCorreoChanged();
    partial void OnusuEstadoChanging(string value);
    partial void OnusuEstadoChanged();
    #endregion
	
	public Usuarios2()
	{
		this._Prestamos = new EntitySet<Prestamos2>(new Action<Prestamos2>(this.attach_Prestamos), new Action<Prestamos2>(this.detach_Prestamos));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDocumento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int usuDocumento
	{
		get
		{
			return this._usuDocumento;
		}
		set
		{
			if ((this._usuDocumento != value))
			{
				this.OnusuDocumentoChanging(value);
				this.SendPropertyChanging();
				this._usuDocumento = value;
				this.SendPropertyChanged("usuDocumento");
				this.OnusuDocumentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string usuNombre
	{
		get
		{
			return this._usuNombre;
		}
		set
		{
			if ((this._usuNombre != value))
			{
				this.OnusuNombreChanging(value);
				this.SendPropertyChanging();
				this._usuNombre = value;
				this.SendPropertyChanged("usuNombre");
				this.OnusuNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDireccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string usuDireccion
	{
		get
		{
			return this._usuDireccion;
		}
		set
		{
			if ((this._usuDireccion != value))
			{
				this.OnusuDireccionChanging(value);
				this.SendPropertyChanging();
				this._usuDireccion = value;
				this.SendPropertyChanged("usuDireccion");
				this.OnusuDireccionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuTelefono", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string usuTelefono
	{
		get
		{
			return this._usuTelefono;
		}
		set
		{
			if ((this._usuTelefono != value))
			{
				this.OnusuTelefonoChanging(value);
				this.SendPropertyChanging();
				this._usuTelefono = value;
				this.SendPropertyChanged("usuTelefono");
				this.OnusuTelefonoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuCorreo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string usuCorreo
	{
		get
		{
			return this._usuCorreo;
		}
		set
		{
			if ((this._usuCorreo != value))
			{
				this.OnusuCorreoChanging(value);
				this.SendPropertyChanging();
				this._usuCorreo = value;
				this.SendPropertyChanged("usuCorreo");
				this.OnusuCorreoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuEstado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string usuEstado
	{
		get
		{
			return this._usuEstado;
		}
		set
		{
			if ((this._usuEstado != value))
			{
				this.OnusuEstadoChanging(value);
				this.SendPropertyChanging();
				this._usuEstado = value;
				this.SendPropertyChanged("usuEstado");
				this.OnusuEstadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios2_Prestamos2", Storage="_Prestamos", ThisKey="usuDocumento", OtherKey="usuDocumento")]
	public EntitySet<Prestamos2> Prestamos2
	{
		get
		{
			return this._Prestamos;
		}
		set
		{
			this._Prestamos.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Prestamos(Prestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Usuarios2 = this;
	}
	
	private void detach_Prestamos(Prestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Usuarios2 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prestamos")]
public partial class Prestamos2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _preCodigo;
	
	private System.DateTime _preFecha;
	
	private int _usuDocumento;
	
	private EntitySet<Sanciones2> _Sanciones;
	
	private EntitySet<DetallePrestamos2> _DetallePrestamos2;
	
	private EntityRef<Usuarios2> _Usuarios2;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    partial void OnpreFechaChanging(System.DateTime value);
    partial void OnpreFechaChanged();
    partial void OnusuDocumentoChanging(int value);
    partial void OnusuDocumentoChanged();
    #endregion
	
	public Prestamos2()
	{
		this._Sanciones = new EntitySet<Sanciones2>(new Action<Sanciones2>(this.attach_Sanciones), new Action<Sanciones2>(this.detach_Sanciones));
		this._DetallePrestamos2 = new EntitySet<DetallePrestamos2>(new Action<DetallePrestamos2>(this.attach_DetallePrestamos2), new Action<DetallePrestamos2>(this.detach_DetallePrestamos2));
		this._Usuarios2 = default(EntityRef<Usuarios2>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int preCodigo
	{
		get
		{
			return this._preCodigo;
		}
		set
		{
			if ((this._preCodigo != value))
			{
				this.OnpreCodigoChanging(value);
				this.SendPropertyChanging();
				this._preCodigo = value;
				this.SendPropertyChanged("preCodigo");
				this.OnpreCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preFecha", DbType="DateTime NOT NULL")]
	public System.DateTime preFecha
	{
		get
		{
			return this._preFecha;
		}
		set
		{
			if ((this._preFecha != value))
			{
				this.OnpreFechaChanging(value);
				this.SendPropertyChanging();
				this._preFecha = value;
				this.SendPropertyChanged("preFecha");
				this.OnpreFechaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDocumento", DbType="Int NOT NULL")]
	public int usuDocumento
	{
		get
		{
			return this._usuDocumento;
		}
		set
		{
			if ((this._usuDocumento != value))
			{
				if (this._Usuarios2.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnusuDocumentoChanging(value);
				this.SendPropertyChanging();
				this._usuDocumento = value;
				this.SendPropertyChanged("usuDocumento");
				this.OnusuDocumentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamos2_Sanciones2", Storage="_Sanciones", ThisKey="preCodigo", OtherKey="preCodigo")]
	public EntitySet<Sanciones2> Sanciones2
	{
		get
		{
			return this._Sanciones;
		}
		set
		{
			this._Sanciones.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamos2_DetallePrestamos", Storage="_DetallePrestamos2", ThisKey="preCodigo", OtherKey="preCodigo")]
	public EntitySet<DetallePrestamos2> DetallePrestamos2
	{
		get
		{
			return this._DetallePrestamos2;
		}
		set
		{
			this._DetallePrestamos2.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios2_Prestamos2", Storage="_Usuarios2", ThisKey="usuDocumento", OtherKey="usuDocumento", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Usuarios2 Usuarios2
	{
		get
		{
			return this._Usuarios2.Entity;
		}
		set
		{
			Usuarios2 previousValue = this._Usuarios2.Entity;
			if (((previousValue != value) 
						|| (this._Usuarios2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Usuarios2.Entity = null;
					previousValue.Prestamos2.Remove(this);
				}
				this._Usuarios2.Entity = value;
				if ((value != null))
				{
					value.Prestamos2.Add(this);
					this._usuDocumento = value.usuDocumento;
				}
				else
				{
					this._usuDocumento = default(int);
				}
				this.SendPropertyChanged("Usuarios2");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Sanciones(Sanciones2 entity)
	{
		this.SendPropertyChanging();
		entity.Prestamos2 = this;
	}
	
	private void detach_Sanciones(Sanciones2 entity)
	{
		this.SendPropertyChanging();
		entity.Prestamos2 = null;
	}
	
	private void attach_DetallePrestamos2(DetallePrestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Prestamos2 = this;
	}
	
	private void detach_DetallePrestamos2(DetallePrestamos2 entity)
	{
		this.SendPropertyChanging();
		entity.Prestamos2 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanciones")]
public partial class Sanciones2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sanCodigo;
	
	private int _sanDiasSancion;
	
	private System.DateTime _sanFechaInicio;
	
	private System.DateTime _sanFechaFin;
	
	private int _preCodigo;
	
	private EntityRef<Prestamos2> _Prestamos;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsanCodigoChanging(int value);
    partial void OnsanCodigoChanged();
    partial void OnsanDiasSancionChanging(int value);
    partial void OnsanDiasSancionChanged();
    partial void OnsanFechaInicioChanging(System.DateTime value);
    partial void OnsanFechaInicioChanged();
    partial void OnsanFechaFinChanging(System.DateTime value);
    partial void OnsanFechaFinChanged();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    #endregion
	
	public Sanciones2()
	{
		this._Prestamos = default(EntityRef<Prestamos2>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sanCodigo
	{
		get
		{
			return this._sanCodigo;
		}
		set
		{
			if ((this._sanCodigo != value))
			{
				this.OnsanCodigoChanging(value);
				this.SendPropertyChanging();
				this._sanCodigo = value;
				this.SendPropertyChanged("sanCodigo");
				this.OnsanCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanDiasSancion", DbType="Int NOT NULL")]
	public int sanDiasSancion
	{
		get
		{
			return this._sanDiasSancion;
		}
		set
		{
			if ((this._sanDiasSancion != value))
			{
				this.OnsanDiasSancionChanging(value);
				this.SendPropertyChanging();
				this._sanDiasSancion = value;
				this.SendPropertyChanged("sanDiasSancion");
				this.OnsanDiasSancionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanFechaInicio", DbType="DateTime NOT NULL")]
	public System.DateTime sanFechaInicio
	{
		get
		{
			return this._sanFechaInicio;
		}
		set
		{
			if ((this._sanFechaInicio != value))
			{
				this.OnsanFechaInicioChanging(value);
				this.SendPropertyChanging();
				this._sanFechaInicio = value;
				this.SendPropertyChanged("sanFechaInicio");
				this.OnsanFechaInicioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanFechaFin", DbType="DateTime NOT NULL")]
	public System.DateTime sanFechaFin
	{
		get
		{
			return this._sanFechaFin;
		}
		set
		{
			if ((this._sanFechaFin != value))
			{
				this.OnsanFechaFinChanging(value);
				this.SendPropertyChanging();
				this._sanFechaFin = value;
				this.SendPropertyChanged("sanFechaFin");
				this.OnsanFechaFinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", DbType="Int NOT NULL")]
	public int preCodigo
	{
		get
		{
			return this._preCodigo;
		}
		set
		{
			if ((this._preCodigo != value))
			{
				if (this._Prestamos.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpreCodigoChanging(value);
				this.SendPropertyChanging();
				this._preCodigo = value;
				this.SendPropertyChanged("preCodigo");
				this.OnpreCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamos2_Sanciones2", Storage="_Prestamos", ThisKey="preCodigo", OtherKey="preCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Prestamos2 Prestamos2
	{
		get
		{
			return this._Prestamos.Entity;
		}
		set
		{
			Prestamos2 previousValue = this._Prestamos.Entity;
			if (((previousValue != value) 
						|| (this._Prestamos.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Prestamos.Entity = null;
					previousValue.Sanciones2.Remove(this);
				}
				this._Prestamos.Entity = value;
				if ((value != null))
				{
					value.Sanciones2.Add(this);
					this._preCodigo = value.preCodigo;
				}
				else
				{
					this._preCodigo = default(int);
				}
				this.SendPropertyChanged("Prestamos2");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetallePrestamos")]
public partial class DetallePrestamos2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dtpPrestamo;
	
	private string _dtpCantidad;
	
	private System.DateTime _dtpFechaFin;
	
	private System.DateTime _dtpFechaDev;
	
	private int _preCodigo;
	
	private int _libCodigo;
	
	private EntityRef<Libros2> _Libros2;
	
	private EntityRef<Prestamos2> _Prestamos2;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndtpPrestamoChanging(int value);
    partial void OndtpPrestamoChanged();
    partial void OndtpCantidadChanging(string value);
    partial void OndtpCantidadChanged();
    partial void OndtpFechaFinChanging(System.DateTime value);
    partial void OndtpFechaFinChanged();
    partial void OndtpFechaDevChanging(System.DateTime value);
    partial void OndtpFechaDevChanged();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    partial void OnlibCodigoChanging(int value);
    partial void OnlibCodigoChanged();
    #endregion
	
	public DetallePrestamos2()
	{
		this._Libros2 = default(EntityRef<Libros2>);
		this._Prestamos2 = default(EntityRef<Prestamos2>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpPrestamo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dtpPrestamo
	{
		get
		{
			return this._dtpPrestamo;
		}
		set
		{
			if ((this._dtpPrestamo != value))
			{
				this.OndtpPrestamoChanging(value);
				this.SendPropertyChanging();
				this._dtpPrestamo = value;
				this.SendPropertyChanged("dtpPrestamo");
				this.OndtpPrestamoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpCantidad", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string dtpCantidad
	{
		get
		{
			return this._dtpCantidad;
		}
		set
		{
			if ((this._dtpCantidad != value))
			{
				this.OndtpCantidadChanging(value);
				this.SendPropertyChanging();
				this._dtpCantidad = value;
				this.SendPropertyChanged("dtpCantidad");
				this.OndtpCantidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpFechaFin", DbType="DateTime NOT NULL")]
	public System.DateTime dtpFechaFin
	{
		get
		{
			return this._dtpFechaFin;
		}
		set
		{
			if ((this._dtpFechaFin != value))
			{
				this.OndtpFechaFinChanging(value);
				this.SendPropertyChanging();
				this._dtpFechaFin = value;
				this.SendPropertyChanged("dtpFechaFin");
				this.OndtpFechaFinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpFechaDev", DbType="DateTime NOT NULL")]
	public System.DateTime dtpFechaDev
	{
		get
		{
			return this._dtpFechaDev;
		}
		set
		{
			if ((this._dtpFechaDev != value))
			{
				this.OndtpFechaDevChanging(value);
				this.SendPropertyChanging();
				this._dtpFechaDev = value;
				this.SendPropertyChanged("dtpFechaDev");
				this.OndtpFechaDevChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", DbType="Int NOT NULL")]
	public int preCodigo
	{
		get
		{
			return this._preCodigo;
		}
		set
		{
			if ((this._preCodigo != value))
			{
				if (this._Prestamos2.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpreCodigoChanging(value);
				this.SendPropertyChanging();
				this._preCodigo = value;
				this.SendPropertyChanged("preCodigo");
				this.OnpreCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libCodigo", DbType="Int NOT NULL")]
	public int libCodigo
	{
		get
		{
			return this._libCodigo;
		}
		set
		{
			if ((this._libCodigo != value))
			{
				if (this._Libros2.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnlibCodigoChanging(value);
				this.SendPropertyChanging();
				this._libCodigo = value;
				this.SendPropertyChanged("libCodigo");
				this.OnlibCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libros2_DetallePrestamos", Storage="_Libros2", ThisKey="libCodigo", OtherKey="libCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Libros2 Libros2
	{
		get
		{
			return this._Libros2.Entity;
		}
		set
		{
			Libros2 previousValue = this._Libros2.Entity;
			if (((previousValue != value) 
						|| (this._Libros2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Libros2.Entity = null;
					previousValue.DetallePrestamos2.Remove(this);
				}
				this._Libros2.Entity = value;
				if ((value != null))
				{
					value.DetallePrestamos2.Add(this);
					this._libCodigo = value.libCodigo;
				}
				else
				{
					this._libCodigo = default(int);
				}
				this.SendPropertyChanged("Libros2");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamos2_DetallePrestamos", Storage="_Prestamos2", ThisKey="preCodigo", OtherKey="preCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Prestamos2 Prestamos2
	{
		get
		{
			return this._Prestamos2.Entity;
		}
		set
		{
			Prestamos2 previousValue = this._Prestamos2.Entity;
			if (((previousValue != value) 
						|| (this._Prestamos2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Prestamos2.Entity = null;
					previousValue.DetallePrestamos2.Remove(this);
				}
				this._Prestamos2.Entity = value;
				if ((value != null))
				{
					value.DetallePrestamos2.Add(this);
					this._preCodigo = value.preCodigo;
				}
				else
				{
					this._preCodigo = default(int);
				}
				this.SendPropertyChanged("Prestamos2");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
