//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Area
{
    public Area()
    {
        this.Libros = new HashSet<Libro>();
    }

    public int areCodigo { get; set; }
    public string areNombre { get; set; }
    public int areTiempo { get; set; }

    public virtual ICollection<Libro> Libros { get; set; }
}

public partial class DetallePrestamo
{
    public int dtpPrestamo { get; set; }
    public string dtpCantidad { get; set; }
    public System.DateTime dtpFechaFin { get; set; }
    public System.DateTime dtpFechaDev { get; set; }
    public int preCodigo { get; set; }
    public int libCodigo { get; set; }

    public virtual Libro Libro { get; set; }
    public virtual Prestamo Prestamo { get; set; }
}

public partial class Libro
{
    public Libro()
    {
        this.DetallePrestamos = new HashSet<DetallePrestamo>();
    }

    public int libCodigo { get; set; }
    public string libNombre { get; set; }
    public int libNumPag { get; set; }
    public string libAutor { get; set; }
    public string libEditorial { get; set; }
    public int areCodigo { get; set; }

    public virtual Area Area { get; set; }
    public virtual ICollection<DetallePrestamo> DetallePrestamos { get; set; }
}

public partial class Prestamo
{
    public Prestamo()
    {
        this.DetallePrestamos = new HashSet<DetallePrestamo>();
        this.Sanciones = new HashSet<Sancione>();
    }

    public int preCodigo { get; set; }
    public System.DateTime preFecha { get; set; }
    public int usuDocumento { get; set; }

    public virtual ICollection<DetallePrestamo> DetallePrestamos { get; set; }
    public virtual Usuario Usuario { get; set; }
    public virtual ICollection<Sancione> Sanciones { get; set; }
}

public partial class Sancione
{
    public int sanCodigo { get; set; }
    public int sanDiasSancion { get; set; }
    public System.DateTime sanFechaInicio { get; set; }
    public System.DateTime sanFechaFin { get; set; }
    public int preCodigo { get; set; }

    public virtual Prestamo Prestamo { get; set; }
}

public partial class Usuario
{
    public Usuario()
    {
        this.Prestamos = new HashSet<Prestamo>();
    }

    public int usuDocumento { get; set; }
    public string usuNombre { get; set; }
    public string usuDireccion { get; set; }
    public string usuTelefono { get; set; }
    public string usuCorreo { get; set; }
    public string usuEstado { get; set; }

    public virtual ICollection<Prestamo> Prestamos { get; set; }
}
