//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlType
    {
        public ControlType()
        {
            this.Controls = new HashSet<Control>();
        }
    
        public string controlTypeID { get; set; }
        public string controlTypeName { get; set; }
    
        public virtual ICollection<Control> Controls { get; set; }
    }
}
