//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public string controlID { get; set; }
        public string controlName { get; set; }
        public string parentControlID { get; set; }
        public string controlTypeID { get; set; }
    
        public virtual ControlType ControlType { get; set; }
    }
}
