//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class securityEntities1 : DbContext
    {
        public securityEntities1()
            : base("name=securityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Control> Control { get; set; }
        public virtual DbSet<ControlType> ControlType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<userAutentication> userAutentication { get; set; }
        public virtual DbSet<UserAutenticationType> UserAutenticationType { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistory { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Usser> Usser { get; set; }
    }
}
